basePath: /
definitions:
  github_com_arfan21_vocagame_internal_model.MidtransNotification:
    properties:
      currency:
        type: string
      fraud_status:
        type: string
      gross_amount:
        type: string
      merchant_id:
        type: string
      order_id:
        type: string
      payment_type:
        type: string
      settlement_time:
        type: string
      signature_key:
        type: string
      status_code:
        type: string
      status_message:
        type: string
      transaction_id:
        type: string
      transaction_status:
        type: string
      transaction_time:
        type: string
    type: object
  github_com_arfan21_vocagame_internal_model.PaymentMethodResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  github_com_arfan21_vocagame_internal_model.ProductResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
      updated_at:
        type: string
    type: object
  github_com_arfan21_vocagame_internal_model.TransactionRequest:
    properties:
      email:
        type: string
      payment_method_id:
        type: integer
      product_id:
        type: string
      quantity:
        minimum: 1
        type: integer
    required:
    - email
    - payment_method_id
    - product_id
    - quantity
    type: object
  github_com_arfan21_vocagame_internal_model.TransactionResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      payment_method:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
      status:
        type: string
      total_price:
        type: number
      updated_at:
        type: string
    type: object
  github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      errors:
        items: {}
        type: array
      message:
        example: Success
        type: string
      status:
        example: OK
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for vocagame.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: vocagame
  version: "1.0"
paths:
  /api/v1/payment-methods:
    get:
      consumes:
      - application/json
      description: Get List Payment Method
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              allOf:
              - $ref: '#/definitions/github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse'
              - properties:
                  data:
                    $ref: '#/definitions/github_com_arfan21_vocagame_internal_model.PaymentMethodResponse'
                type: object
            type: array
      summary: Get List Payment Method
      tags:
      - Payment Method
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get List Product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              allOf:
              - $ref: '#/definitions/github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse'
              - properties:
                  data:
                    $ref: '#/definitions/github_com_arfan21_vocagame_internal_model.ProductResponse'
                type: object
            type: array
      summary: Get List Product
      tags:
      - Product
  /api/v1/transactions:
    post:
      consumes:
      - application/json
      description: Create Transaction
      parameters:
      - description: Transaction Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_vocagame_internal_model.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_vocagame_internal_model.TransactionResponse'
              type: object
      summary: Create Transaction
      tags:
      - Transaction
  /api/v1/transactions/callback/midtrans:
    post:
      consumes:
      - application/json
      description: Midtrans Notification
      parameters:
      - description: Midtrans Notification Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_vocagame_internal_model.MidtransNotification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse'
      summary: Midtrans Notification
      tags:
      - Transaction
  /api/v1/transactions/callback/success:
    get:
      consumes:
      - application/json
      description: Transaction Success Callback
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse'
      summary: Transaction Success Callback
      tags:
      - Transaction
  /api/v1/transactions/tracking:
    get:
      consumes:
      - application/json
      description: Transaction Tracking Status
      parameters:
      - description: Phone Number
        in: query
        name: phone_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_vocagame_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_vocagame_internal_model.TransactionResponse'
              type: object
      summary: Transaction Tracking Status
      tags:
      - Transaction
swagger: "2.0"
